# Generated by Django 4.0.4 on 2022-08-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, unique=True, verbose_name='Уровень доступа')),
                ('info', models.TextField(blank=True, verbose_name='Доступные функции')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('info', models.TextField(blank=True, verbose_name='Подробная информация')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('finish_time', models.TimeField(verbose_name='Время завершения')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('status', models.BooleanField(verbose_name='Активно')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='telegram_bot.event', verbose_name='Мероприятие')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='telegram_bot.access', verbose_name='Уровень доступа')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('info', models.TextField(blank=True, verbose_name='О себе')),
                ('telegram_id', models.CharField(max_length=10, unique=True, verbose_name='ID в Telegram')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='telegram_bot.event', verbose_name='Мероприятие')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=10, verbose_name='Опыт работы')),
                ('language', models.CharField(max_length=10, verbose_name='Основной язык разработки')),
                ('other_expecting', models.BooleanField(verbose_name='Ждем других анкет?')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='telegram_bot.participant', verbose_name='Участник')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('info', models.TextField(blank=True, verbose_name='Подробная информация')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='presentations', to='telegram_bot.block', verbose_name='Блок')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='telegram_bot.user', verbose_name='Спикер')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='telegram_bot.user', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='telegram_bot.user', verbose_name='Организатор'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reject', models.BooleanField(verbose_name='Отклонен')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Сумма доната')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='telegram_bot.event', verbose_name='Мероприятие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='telegram_bot.participant', verbose_name='Участник')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderating_blocks', to='telegram_bot.user', verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='block',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='blocks', to='telegram_bot.section', verbose_name='Секция'),
        ),
    ]
