# Generated by Django 4.0.4 on 2022-08-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'уровень доступа', 'verbose_name_plural': 'уровни доступа'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'блок', 'verbose_name_plural': 'блоки'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Донат', 'verbose_name_plural': 'Донаты'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'мероприятие', 'verbose_name_plural': 'мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'участник', 'verbose_name_plural': 'участники'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'выступление', 'verbose_name_plural': 'выступления'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'анкета', 'verbose_name_plural': 'анкеты'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'часть', 'verbose_name_plural': 'части'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
