# Generated by Django 4.0.4 on 2022-08-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_access_options_alter_block_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BotUser',
        ),
    ]
