# Generated by Django 4.0.4 on 2022-08-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_botuser_company_postion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='company_postion',
            new_name='company_position',
        ),
    ]
