# Generated by Django 4.0.4 on 2022-08-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_rename_company_postion_botuser_company_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='company_position',
            field=models.CharField(blank=True, max_length=50, verbose_name='Комания и должность'),
        ),
    ]
