# Generated by Django 4.0.4 on 2022-08-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_alter_botuser_company_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='company_position',
        ),
        migrations.AddField(
            model_name='botuser',
            name='companyposition',
            field=models.CharField(blank=True, max_length=50, verbose_name='Комания, в которой работет'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='position',
            field=models.CharField(blank=True, max_length=50, verbose_name='Должность'),
        ),
    ]
