# Generated by Django 4.0.4 on 2022-08-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_remove_botuser_company_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='companyposition',
            new_name='company',
        ),
    ]
