# Generated by Django 4.0.4 on 2022-08-05 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_alter_participant_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_for', to='telegram_bot.participant', verbose_name='Вопрос кому')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_from', to='telegram_bot.participant', verbose_name='От кого вопрос')),
            ],
        ),
    ]
