# Generated by Django 4.0.4 on 2022-08-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='telegram_bot.participant', verbose_name='Спикер'),
        ),
    ]
