# Generated by Django 4.0.4 on 2022-08-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_alter_botuser_name_alter_botuser_surname_and_more'),
        ('telegram_bot', '0013_alter_question_text_alter_question_user'),
    ]

    operations = [
    ]
