# Generated by Django 4.0.4 on 2022-08-06 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0014_merge_20220806_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='block',
            name='speaker',
        ),
        migrations.AlterField(
            model_name='block',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderating_blocks', to='telegram_bot.participant', verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='block',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='telegram_bot.section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='telegram_bot.block', verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='telegram_bot.participant', verbose_name='Спикер'),
        ),
        migrations.AlterField(
            model_name='question',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='got_questions', to='telegram_bot.participant', verbose_name='Вопрос кому'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='telegram_bot.participant', verbose_name='От кого вопрос'),
        ),
    ]
