# Generated by Django 4.0.4 on 2022-08-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0014_merge_20220806_1405'),
        ('telegram_bot', '0016_rename_user_question_participant'),
    ]

    operations = [
    ]
